"""add updated_at field to ascents table

Revision ID: 186c35365b3c
Revises: add_remote_boulder_tables
Create Date: 2025-05-07 08:03:40.011677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186c35365b3c'
down_revision: Union[str, None] = 'add_remote_boulder_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_migrations')
    op.add_column('ascents',
                  sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('remote_boulder_bonus',
                  sa.Column('inserted_at', sa.DateTime(), nullable=False))
    op.add_column('remote_boulder_bonus',
                  sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_remote_boulder_bonus_boulder_id'),
                    'remote_boulder_bonus', ['boulder_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remote_boulder_bonus_boulder_id'),
                  table_name='remote_boulder_bonus')
    op.drop_column('remote_boulder_bonus', 'updated_at')
    op.drop_column('remote_boulder_bonus', 'inserted_at')
    op.drop_column('ascents', 'updated_at')
    op.create_table(
        'schema_migrations',
        sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column('inserted_at',
                  postgresql.TIMESTAMP(precision=0),
                  autoincrement=False,
                  nullable=True),
        sa.PrimaryKeyConstraint('version', name='schema_migrations_pkey'))
    # ### end Alembic commands ###
