"""Remove normalized_volume_bonus

Revision ID: b6573377c445
Revises: 045fe5c335f1
Create Date: 2025-05-16 12:33:16.325037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6573377c445'
down_revision: Union[str, None] = '045fe5c335f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marathon_detailed_results', 'normalized_volume_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marathon_detailed_results', sa.Column('normalized_volume_bonus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
