"""add unique indexes on ascents table

Revision ID: da8d5e5ad591
Revises: 186c35365b3c
Create Date: 2025-05-08 07:16:47.980684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8d5e5ad591'
down_revision: Union[str, None] = '186c35365b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_ascent_per_competition', 'ascents', ['participant_id', 'route_id', 'competition_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ascent_per_competition', 'ascents', type_='unique')
    # ### end Alembic commands ###
